runtime: python-compat
vm: true
api_version: 1
threadsafe: true

# [START handlers]
handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /bootstrap
  static_dir: bootstrap

- url: /_tasks/blockLoader
  script: events.app
  login: admin

- url: /.*
  script: blockhooks.app
# [END handlers]
